language: php

php:
  - 5.5

before_script:
  - composer install --dev --prefer-source
  - export PATH=./vendor/bin:$PATH

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpcs --standard=PSR2 src tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
